apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: 2018-06-11T17:36:22Z
  generation: 4
  labels:
    run: beer-order-server-deployment
  name: beer-order-server-deployment
  namespace: default
  resourceVersion: "91482"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/beer-order-server-deployment
  uid: f516add0-6d9d-11e8-8eea-0800270c10be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: beer-order-server-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: beer-order-server-deployment
    spec:
      containers:
      - image: kkocs/beer-order-server:4.0
        imagePullPolicy: IfNotPresent
        env:
            - name: ORDER_SERVER_MYSQL_DB_HOST
              valueFrom:
                  secretKeyRef:
                      name: beer-order-server-mysql-secret 
                      key: database
            - name: ORDER_SERVER_MYSQL_DB_USER
              valueFrom:
                  secretKeyRef:
                      name: beer-order-server-mysql-secret
                      key: username
            - name: ORDER_SERVER_MYSQL_DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: beer-order-server-mysql-secret
                      key: password
        name: beer-order-server-deployment
        ports:
        - containerPort: 8100
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30